### ISSUE TITLE
Klickbra länkar till kontaktuppgifter

### ISSUE THREAD

**Issue by kimalekst** [Bergssen/nikola.bergsen.github.io#1]
Kontaktuppgifter är en bild

**Comment by Bergssen** [comment]
Yes, bara tillfälligt, kommer fixa så mejladressen är länkat till en "mailto" och profilnamnet till kanske linkedin.. och typ arbetsplatsen till SCB:s hemsidan.

**Comment by Bergssen** [comment]
Löst, ny uppdatering med flatly.css (https://bootswatch.com/) samt ditt förslag från fontawesome.
